# Generated by Django 5.0.1 on 2026-01-06 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['user', 'position'], name='columns_col_user_id_09b1b3_idx')],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
